[platformio]
src_dir = src
default_envs = bench_air_node_i2c_scanner

[env]
platform = espressif32@6.7.0
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SHT4x Library@^1.0.5
  adafruit/Adafruit BME680 Library@^2.0.5
  adafruit/Adafruit Unified Sensor@^1.1.14

[env:bench_air_node_i2c_scanner]
build_src_filter =
  -<*>
  +<bench_air_node_i2c_scanner.cpp>

[env:bench_air_node_serial_json]
build_src_filter =
  -<*>
  +<bench_air_node_serial_json.cpp>
