[platformio]
src_dir = src
default_envs = flood_node_adc_smoke_test

[env]
platform = espressif32@6.7.0
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200

[env:flood_node_adc_smoke_test]
build_src_filter =
  -<*>
  +<flood_node_adc_smoke_test.cpp>

[env:flood_node_serial_json]
build_src_filter =
  -<*>
  +<flood_node_serial_json.cpp>
