[platformio]
src_dir = src
default_envs = circuit_monitor_pzem_test

[env]
platform = espressif32@6.7.0
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
lib_deps =
  mandreev/PZEM-004T-v30@^1.1.2

[env:circuit_monitor_pzem_test]
build_src_filter =
  -<*>
  +<circuit_monitor_pzem_test.cpp>

[env:circuit_monitor_address_change]
build_src_filter =
  -<*>
  +<circuit_monitor_address_change.cpp>

[env:circuit_monitor_serial_json]
build_src_filter =
  -<*>
  +<circuit_monitor_serial_json.cpp>
